version: '3'
services:
  node_app:
    build: .
    volumes:
      - ./:/app:ro
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - PORT=4000

  mongo:
    image: mongo 
    volumes:
      - mongo_db:/data/db
  mysql:
    image: mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: "Pratik@123"
    volumes:
      - mysql_db:/var/lib/mysql

   
    
volumes:
  mongo_db:
  mysql_db: